name: PR Test Review

on:
  pull_request:
    paths:
      - "**/*.kt"

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch Changed Test Files
        id: get_files
        run: |
          git fetch --all
          BASE_BRANCH=$(git branch -r | grep -E 'origin/main|origin/master' | head -n 1 | awk -F'/' '{print $2}')
          CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH...HEAD -- '*.kt' || echo "")
          echo "FILES=$CHANGED_FILES" >> $GITHUB_ENV
        shell: bash

      - name: Debug Changed Files
        run: echo "Changed files: $FILES"

      - name: Run Test Review
        if: env.FILES != ''
        run: python cli/test_checker.py $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
