name: PR Test Review

on:
  pull_request:
    paths:
      - "**/*.kt"

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch Changed Test Files
        id: get_files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep '\.kt$' | tr '\n' ' ')
          echo "FILES=$CHANGED_FILES" >> $GITHUB_ENV
        shell: bash

      - name: Run Test Review
        run: python cli/test_checker.py $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
