name: Test and Review

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for git diff

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Ensure Gradle Wrapper Exists
        run: |
          if [ ! -f ./gradlew ]; then
            echo "Gradle wrapper not found! Initializing Gradle..."
            gradle wrapper
          fi
          chmod +x ./gradlew  # Ensure the Gradle wrapper is executable

      - name: Fetch Base Branch
        run: |
          git fetch origin main || git fetch origin master  # Ensure base branch is available

          # Determine the base branch dynamically
          if git branch -r | grep -q "origin/main"; then
              BASE_BRANCH="origin/main"
          elif git branch -r | grep -q "origin/master"; then
              BASE_BRANCH="origin/master"
          else
              echo "Error: Neither origin/main nor origin/master found!" >&2
              exit 1
          fi

          # Get changed Kotlin files
          CHANGED_FILES=$(git diff --name-only $BASE_BRANCH...HEAD -- '*.kt' | tr '\n' ' ')
          echo "FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run Lint Check
        if: env.FILES != ''
        run: |
          echo "Running lint check on modified Kotlin files..."
          ./gradlew ktlintCheck

      - name: Run Tests
        if: env.FILES != ''
        run: |
          echo "Running tests for modified Kotlin files..."
          ./gradlew test
